export const DEFAULT_MAX_REPOSITORY_TREE_ENTRIES = 300;
export const DEFAULT_MAX_FILE_METADATA_ENTRIES = 150;
export const DEFAULT_MAX_FILE_CONTENT_CHARS = 24_000;
export const DEFAULT_MAX_CHUNK_PLAN_ENTRIES = 75;
