import type {
  SecurityKnowledgeBaseCategory,
  SecurityKnowledgeBaseCodeExample,
  SecurityKnowledgeBaseReference,
  SecurityKnowledgeBaseRule,
  SecurityKnowledgeBaseSeverity,
} from "./security-knowledge-base.types";

type RuleSpec = {
  id: string;
  title: string;
  category: SecurityKnowledgeBaseCategory;
  severity: SecurityKnowledgeBaseSeverity;
  owasp: string;
  cwe: string | null;
  description: string;
  businessImpact?: string;
  technicalImpact?: string;
  remediationSteps?: string[];
  secureCodingRecommendations?: string[];
  codeExample?: SecurityKnowledgeBaseCodeExample;
  externalReferences?: SecurityKnowledgeBaseReference[];
  confidenceScore: number;
  tags?: string[];
};

const OWASP_TOP_10_REFERENCE = {
  title: "OWASP Top 10",
  url: "https://owasp.org/www-project-top-ten/",
};

const OWASP_CHEAT_SHEET_REFERENCE = {
  title: "OWASP Cheat Sheet Series",
  url: "https://cheatsheetseries.owasp.org/",
};

const CWE_REFERENCE = {
  title: "MITRE CWE",
  url: "https://cwe.mitre.org/",
};

const CATEGORY_BUSINESS_IMPACT: Record<SecurityKnowledgeBaseCategory, string> = {
  authentication:
    "Attackers may compromise user accounts, bypass identity controls, or erode customer trust in the platform.",
  authorization:
    "Attackers may access or modify another tenant's data, creating privacy, compliance, and contractual exposure.",
  csrf:
    "Users may be tricked into performing unwanted state-changing actions while authenticated.",
  express:
    "A weak API foundation increases the likelihood of data exposure, denial of service, and operational incidents.",
  helmet:
    "Missing browser security headers can increase exploitability of client-side and transport-layer weaknesses.",
  cors:
    "Overly broad browser trust boundaries can expose authenticated APIs to untrusted web origins.",
  injection:
    "Injection flaws can lead to data theft, remote code execution, service compromise, and regulatory exposure.",
  jwt:
    "Weak token controls can let attackers impersonate users or extend sessions beyond intended limits.",
  logging:
    "Sensitive logging can expose customer data, while missing audit trails can delay incident response.",
  prisma:
    "Unsafe ORM usage can leak tenant data, corrupt records, or bypass expected application boundaries.",
  rate_limiting:
    "Abuse controls that are missing or too loose can enable credential attacks, scraping, and cost amplification.",
  react:
    "Unsafe frontend patterns can expose users to phishing, XSS, token theft, or malicious redirects.",
  secrets:
    "Leaked credentials can enable direct compromise of cloud accounts, databases, third-party APIs, or signing keys.",
  sql_injection:
    "SQL injection can expose or modify production data and may become a full application compromise.",
  validation:
    "Untrusted inputs can reach business logic in unexpected shapes, causing security defects and reliability issues.",
  xss:
    "Cross-site scripting can steal session data, perform actions as users, or alter application content.",
};

const CATEGORY_TECHNICAL_IMPACT: Record<SecurityKnowledgeBaseCategory, string> = {
  authentication: "The application does not reliably establish or preserve the user's identity boundary.",
  authorization: "Object, route, or tenant-level access checks can be bypassed or are missing.",
  csrf: "State-changing routes depend only on ambient browser cookies without a per-request anti-CSRF signal.",
  express: "Express middleware or error handling is missing hardening expected for internet-facing APIs.",
  helmet: "Security-related HTTP response headers are absent, disabled, or weakened.",
  cors: "Cross-origin policy allows unexpected origins or unsafe credential sharing.",
  injection: "Untrusted input can influence code, command, query, or interpreter execution.",
  jwt: "JWT verification, signing, storage, or expiration controls are incomplete.",
  logging: "Logs may contain secrets/PII or lack security-relevant audit events.",
  prisma: "Prisma access patterns may bypass tenant scoping, parameterization, or consistency guarantees.",
  rate_limiting: "Endpoints lack request throttling or have insufficient abuse boundaries.",
  react: "React rendering or navigation trusts attacker-controllable values.",
  secrets: "Credentials or private key material are present in source or runtime-accessible client code.",
  sql_injection: "SQL text or query fragments can be influenced by untrusted data.",
  validation: "Inputs are accepted without strict schema validation, normalization, and bounds checking.",
  xss: "Untrusted markup, script-capable content, or DOM sinks are reachable from application data.",
};

const DEFAULT_REMEDIATION_STEPS: Record<SecurityKnowledgeBaseCategory, string[]> = {
  authentication: [
    "Define the expected identity and session boundary.",
    "Add server-side checks for the affected flow.",
    "Add regression tests for invalid, expired, and attacker-controlled credentials.",
  ],
  authorization: [
    "Enforce ownership or role checks in the repository/service query.",
    "Deny access by default when the actor or resource cannot be resolved.",
    "Add tests for cross-user and cross-tenant access attempts.",
  ],
  csrf: [
    "Require CSRF tokens or SameSite-protected cookies for state-changing requests.",
    "Reject unsafe methods that do not include the anti-CSRF signal.",
    "Add tests for cross-origin form and fetch attempts.",
  ],
  express: [
    "Add the missing middleware or hardening control near application initialization.",
    "Use centralized configuration rather than inline permissive defaults.",
    "Add integration tests for security headers, payload limits, and error responses.",
  ],
  helmet: [
    "Install and apply Helmet during Express initialization.",
    "Tune CSP and related headers for the deployed frontend and API.",
    "Verify expected headers in an integration test.",
  ],
  cors: [
    "Replace wildcard origins with an allowlist from configuration.",
    "Avoid credentials with wildcard or reflected origins.",
    "Add tests for trusted and untrusted origins.",
  ],
  injection: [
    "Remove dynamic interpreter execution or isolate it behind a strict allowlist.",
    "Validate and normalize all untrusted inputs before use.",
    "Add tests with metacharacters and malicious payloads.",
  ],
  jwt: [
    "Use strong signing keys and strict verification options.",
    "Set short access-token lifetimes and validate issuer/audience.",
    "Add tests for expired, unsigned, and wrong-audience tokens.",
  ],
  logging: [
    "Remove secrets and PII from log statements.",
    "Use structured logging with redaction.",
    "Add audit events for security-sensitive actions.",
  ],
  prisma: [
    "Use Prisma-safe query APIs and tenant-scoped filters.",
    "Wrap multi-step critical writes in transactions.",
    "Add tests proving another user's records cannot be read or changed.",
  ],
  rate_limiting: [
    "Apply rate limits to authentication, upload, import, and scan endpoints.",
    "Use identity-aware keys when a user is authenticated.",
    "Monitor rate-limit rejections and tune thresholds.",
  ],
  react: [
    "Avoid trusting user-controlled data in DOM sinks or navigation targets.",
    "Use framework escaping and allowlisted URLs.",
    "Add component tests for unsafe input rendering.",
  ],
  secrets: [
    "Remove the secret from source control and rotate it.",
    "Load secrets from environment variables or a managed secret store.",
    "Add secret scanning to pre-commit and CI.",
  ],
  sql_injection: [
    "Replace string-built SQL with parameterized queries or ORM filters.",
    "Validate query inputs with strict schemas.",
    "Add tests using SQL metacharacters and tautology payloads.",
  ],
  validation: [
    "Create strict schemas for params, query strings, and request bodies.",
    "Reject unknown fields unless explicitly required.",
    "Add tests for malformed, oversized, and type-confused inputs.",
  ],
  xss: [
    "Remove direct HTML/DOM injection or sanitize with a proven sanitizer.",
    "Prefer text rendering and framework escaping.",
    "Add tests using script, event-handler, and URL-based XSS payloads.",
  ],
};

const DEFAULT_SECURE_CODING_RECOMMENDATIONS: Record<SecurityKnowledgeBaseCategory, string[]> = {
  authentication: ["Use centralized auth middleware.", "Use constant-time token comparisons where applicable."],
  authorization: ["Make ownership checks part of every data access method.", "Never trust resource IDs from the client alone."],
  csrf: ["Use SameSite cookies.", "Require CSRF tokens for cookie-authenticated mutation requests."],
  express: ["Centralize middleware setup.", "Prefer secure defaults in config and fail closed in production."],
  helmet: ["Apply Helmet early.", "Treat CSP as an application-specific allowlist."],
  cors: ["Use explicit origins.", "Keep credentials disabled unless required."],
  injection: ["Avoid dynamic execution.", "Use allowlists instead of deny lists."],
  jwt: ["Use asymmetric keys or high-entropy secrets.", "Validate issuer, audience, expiration, and algorithm."],
  logging: ["Redact secrets.", "Log security events without logging sensitive payloads."],
  prisma: ["Use typed Prisma APIs.", "Keep user ownership filters in repositories."],
  rate_limiting: ["Protect expensive routes.", "Use separate limits for auth and uploads."],
  react: ["Let React escape text.", "Validate external links and redirects."],
  secrets: ["Never commit real credentials.", "Rotate any exposed credential immediately."],
  sql_injection: ["Use parameter binding.", "Keep raw SQL rare and reviewed."],
  validation: ["Validate at the boundary.", "Prefer strict schemas and bounded inputs."],
  xss: ["Avoid HTML sinks.", "Sanitize rich text before rendering."],
};

const DEFAULT_CODE_EXAMPLES: Record<SecurityKnowledgeBaseCategory, SecurityKnowledgeBaseCodeExample> = {
  authentication: {
    language: "typescript",
    vulnerable: "router.post('/login', loginController);",
    secure: "router.post('/login', rateLimit(authLimit), validateRequest({ body: loginSchema }), loginController);",
  },
  authorization: {
    language: "typescript",
    vulnerable: "return prisma.project.findUnique({ where: { id: projectId } });",
    secure: "return prisma.project.findFirst({ where: { id: projectId, ownerId: actorId, deletedAt: null } });",
  },
  csrf: {
    language: "typescript",
    vulnerable: "app.post('/billing/card', updateCard);",
    secure: "app.post('/billing/card', csrfProtection, updateCard);",
  },
  express: {
    language: "typescript",
    vulnerable: "app.use(express.json());",
    secure: "app.use(express.json({ limit: environment.requestBodyLimit }));",
  },
  helmet: {
    language: "typescript",
    vulnerable: "const app = express();",
    secure: "const app = express();\napp.use(helmet());",
  },
  cors: {
    language: "typescript",
    vulnerable: "app.use(cors());",
    secure: "app.use(cors({ origin: environment.corsOrigins, credentials: true }));",
  },
  injection: {
    language: "typescript",
    vulnerable: "eval(request.body.expression);",
    secure: "const operation = allowedOperations[request.body.operation];\noperation(validatedInput);",
  },
  jwt: {
    language: "typescript",
    vulnerable: "jwt.verify(token, secret);",
    secure: "jwt.verify(token, secret, { algorithms: ['HS256'], issuer, audience });",
  },
  logging: {
    language: "typescript",
    vulnerable: "logger.info('login', { password: input.password });",
    secure: "logger.info('login', { userId: user.id, result: 'success' });",
  },
  prisma: {
    language: "typescript",
    vulnerable: "return prisma.project.findUnique({ where: { id } });",
    secure: "return prisma.project.findFirst({ where: { id, ownerId: actorId } });",
  },
  rate_limiting: {
    language: "typescript",
    vulnerable: "router.post('/auth/login', login);",
    secure: "router.post('/auth/login', authRateLimiter, login);",
  },
  react: {
    language: "tsx",
    vulnerable: "<a href={url} target=\"_blank\">Open</a>",
    secure: "<a href={safeUrl} target=\"_blank\" rel=\"noopener noreferrer\">Open</a>",
  },
  secrets: {
    language: "typescript",
    vulnerable: "const jwtSecret = 'super-secret-value';",
    secure: "const jwtSecret = environment.jwt.accessSecret;",
  },
  sql_injection: {
    language: "typescript",
    vulnerable: "await prisma.$queryRawUnsafe(`SELECT * FROM users WHERE email = '${email}'`);",
    secure: "await prisma.user.findUnique({ where: { email: validatedEmail } });",
  },
  validation: {
    language: "typescript",
    vulnerable: "router.post('/projects', createProject);",
    secure: "router.post('/projects', validateRequest({ body: createProjectSchema }), createProject);",
  },
  xss: {
    language: "tsx",
    vulnerable: "<div dangerouslySetInnerHTML={{ __html: content }} />",
    secure: "<div>{content}</div>",
  },
};

const RULE_SPECS: RuleSpec[] = [
  {
    id: "secret.jwt-secret",
    title: "Hardcoded JWT secret",
    category: "secrets",
    severity: "HIGH",
    owasp: "A02:2021 - Cryptographic Failures",
    cwe: "CWE-798",
    description: "JWT signing material appears in source code instead of a managed runtime secret.",
    confidenceScore: 0.95,
    tags: ["existing-rule", "jwt", "secret"],
  },
  {
    id: "secret.generic-api-key",
    title: "Hardcoded API key or token",
    category: "secrets",
    severity: "HIGH",
    owasp: "A02:2021 - Cryptographic Failures",
    cwe: "CWE-798",
    description: "A credential-like token or API key appears to be committed to the repository.",
    confidenceScore: 0.82,
    tags: ["existing-rule", "secret"],
  },
  {
    id: "secret.aws-access-key",
    title: "Hardcoded AWS access key",
    category: "secrets",
    severity: "CRITICAL",
    owasp: "A02:2021 - Cryptographic Failures",
    cwe: "CWE-798",
    description: "An AWS access key pattern is present in source code and may grant cloud account access.",
    confidenceScore: 0.98,
    tags: ["existing-rule", "aws", "cloud"],
  },
  {
    id: "secret.private-key",
    title: "Private key material committed",
    category: "secrets",
    severity: "CRITICAL",
    owasp: "A02:2021 - Cryptographic Failures",
    cwe: "CWE-321",
    description: "Private key material was found in the repository and must be treated as compromised.",
    confidenceScore: 0.99,
    tags: ["existing-rule", "private-key"],
  },
  {
    id: "logging.console-log",
    title: "Console logging in production code",
    category: "logging",
    severity: "LOW",
    owasp: "A09:2021 - Security Logging and Monitoring Failures",
    cwe: "CWE-532",
    description: "Console logging can leak sensitive values and bypass centralized redaction policies.",
    confidenceScore: 0.72,
    tags: ["existing-rule", "logging"],
  },
  {
    id: "injection.eval",
    title: "Use of eval",
    category: "injection",
    severity: "CRITICAL",
    owasp: "A03:2021 - Injection",
    cwe: "CWE-95",
    description: "Dynamic code execution through eval can become remote code execution when influenced by input.",
    confidenceScore: 0.97,
    tags: ["existing-rule", "rce"],
  },
  {
    id: "xss.dangerously-set-inner-html",
    title: "dangerouslySetInnerHTML usage",
    category: "xss",
    severity: "HIGH",
    owasp: "A03:2021 - Injection",
    cwe: "CWE-79",
    description: "React HTML injection can execute attacker-controlled script when content is not sanitized.",
    confidenceScore: 0.9,
    tags: ["existing-rule", "react", "xss"],
  },
  {
    id: "database.query-raw-unsafe",
    title: "Unsafe Prisma raw query",
    category: "prisma",
    severity: "CRITICAL",
    owasp: "A03:2021 - Injection",
    cwe: "CWE-89",
    description: "Prisma queryRawUnsafe can execute SQL built from attacker-controlled strings.",
    confidenceScore: 0.96,
    tags: ["existing-rule", "prisma", "sql"],
  },
  {
    id: "database.query-raw",
    title: "Raw Prisma query requires review",
    category: "prisma",
    severity: "MEDIUM",
    owasp: "A03:2021 - Injection",
    cwe: "CWE-89",
    description: "Raw Prisma queries must be parameterized and reviewed because they bypass normal ORM safeguards.",
    confidenceScore: 0.74,
    tags: ["existing-rule", "prisma", "sql"],
  },
  {
    id: "process.exec",
    title: "Shell command execution",
    category: "injection",
    severity: "HIGH",
    owasp: "A03:2021 - Injection",
    cwe: "CWE-78",
    description: "Child process shell execution can become command injection when arguments include untrusted data.",
    confidenceScore: 0.91,
    tags: ["existing-rule", "command-injection"],
  },
  {
    id: "process.spawn",
    title: "Process spawn usage",
    category: "injection",
    severity: "MEDIUM",
    owasp: "A03:2021 - Injection",
    cwe: "CWE-78",
    description: "Spawning commands requires strict executable and argument allowlists.",
    confidenceScore: 0.78,
    tags: ["existing-rule", "command-injection"],
  },
  {
    id: "config.missing-helmet",
    title: "Missing Helmet middleware",
    category: "helmet",
    severity: "HIGH",
    owasp: "A05:2021 - Security Misconfiguration",
    cwe: "CWE-693",
    description: "Express is used without Helmet, leaving security response headers unset by default.",
    confidenceScore: 0.84,
    tags: ["existing-rule", "express"],
  },
  {
    id: "config.missing-rate-limiter",
    title: "Missing API rate limiter",
    category: "rate_limiting",
    severity: "HIGH",
    owasp: "A04:2021 - Insecure Design",
    cwe: "CWE-770",
    description: "Public API routes do not appear to use rate limiting to slow brute force and abuse.",
    confidenceScore: 0.82,
    tags: ["existing-rule", "express"],
  },
  {
    id: "validation.missing-input-validation",
    title: "Missing request validation",
    category: "validation",
    severity: "MEDIUM",
    owasp: "A04:2021 - Insecure Design",
    cwe: "CWE-20",
    description: "Mutation routes appear to accept request data without schema validation at the boundary.",
    confidenceScore: 0.8,
    tags: ["existing-rule", "zod"],
  },
  {
    id: "config.weak-cors",
    title: "Weak CORS policy",
    category: "cors",
    severity: "MEDIUM",
    owasp: "A05:2021 - Security Misconfiguration",
    cwe: "CWE-942",
    description: "CORS configuration appears to allow broad or wildcard origins.",
    confidenceScore: 0.82,
    tags: ["existing-rule", "express"],
  },
  {
    id: "auth.password-plaintext-storage",
    title: "Plaintext password storage",
    category: "authentication",
    severity: "CRITICAL",
    owasp: "A07:2021 - Identification and Authentication Failures",
    cwe: "CWE-256",
    description: "Passwords are stored or compared without a slow password hashing algorithm.",
    confidenceScore: 0.94,
  },
  {
    id: "auth.weak-password-policy",
    title: "Weak password policy",
    category: "authentication",
    severity: "MEDIUM",
    owasp: "A07:2021 - Identification and Authentication Failures",
    cwe: "CWE-521",
    description: "The application allows weak passwords or does not enforce minimum password quality.",
    confidenceScore: 0.76,
  },
  {
    id: "auth.missing-account-lockout",
    title: "Missing account lockout controls",
    category: "authentication",
    severity: "MEDIUM",
    owasp: "A07:2021 - Identification and Authentication Failures",
    cwe: "CWE-307",
    description: "Repeated login failures are not slowed or locked, enabling credential attacks.",
    confidenceScore: 0.74,
  },
  {
    id: "auth.missing-mfa-sensitive-action",
    title: "Missing step-up authentication",
    category: "authentication",
    severity: "MEDIUM",
    owasp: "A07:2021 - Identification and Authentication Failures",
    cwe: "CWE-308",
    description: "Sensitive account or billing changes do not require stronger recent authentication.",
    confidenceScore: 0.68,
  },
  {
    id: "auth.insecure-session-cookie",
    title: "Insecure session cookie attributes",
    category: "authentication",
    severity: "HIGH",
    owasp: "A05:2021 - Security Misconfiguration",
    cwe: "CWE-614",
    description: "Session or refresh cookies are missing HttpOnly, Secure, SameSite, or scoped path attributes.",
    confidenceScore: 0.86,
  },
  {
    id: "auth.refresh-token-not-rotated",
    title: "Refresh token rotation missing",
    category: "authentication",
    severity: "HIGH",
    owasp: "A07:2021 - Identification and Authentication Failures",
    cwe: "CWE-613",
    description: "Refresh tokens are reused instead of rotated, reducing replay detection.",
    confidenceScore: 0.82,
  },
  {
    id: "auth.user-enumeration",
    title: "User enumeration through authentication errors",
    category: "authentication",
    severity: "LOW",
    owasp: "A07:2021 - Identification and Authentication Failures",
    cwe: "CWE-203",
    description: "Login or recovery responses reveal whether an account exists.",
    confidenceScore: 0.7,
  },
  {
    id: "authorization.missing-route-guard",
    title: "Missing route authorization guard",
    category: "authorization",
    severity: "HIGH",
    owasp: "A01:2021 - Broken Access Control",
    cwe: "CWE-862",
    description: "A protected route or controller appears reachable without authorization middleware.",
    confidenceScore: 0.84,
  },
  {
    id: "authorization.idor",
    title: "Insecure direct object reference",
    category: "authorization",
    severity: "HIGH",
    owasp: "A01:2021 - Broken Access Control",
    cwe: "CWE-639",
    description: "Resource access is based on client-supplied IDs without ownership validation.",
    confidenceScore: 0.88,
  },
  {
    id: "authorization.broken-object-level",
    title: "Broken object-level authorization",
    category: "authorization",
    severity: "HIGH",
    owasp: "A01:2021 - Broken Access Control",
    cwe: "CWE-863",
    description: "The application does not consistently enforce object-level permission checks.",
    confidenceScore: 0.85,
  },
  {
    id: "authorization.privilege-escalation",
    title: "Privilege escalation risk",
    category: "authorization",
    severity: "CRITICAL",
    owasp: "A01:2021 - Broken Access Control",
    cwe: "CWE-269",
    description: "Role, plan, or permission updates can be influenced without sufficient administrative checks.",
    confidenceScore: 0.86,
  },
  {
    id: "jwt.alg-none",
    title: "JWT algorithm confusion",
    category: "jwt",
    severity: "CRITICAL",
    owasp: "A07:2021 - Identification and Authentication Failures",
    cwe: "CWE-347",
    description: "JWT verification does not pin expected signing algorithms.",
    confidenceScore: 0.9,
  },
  {
    id: "jwt.missing-expiration",
    title: "JWT missing expiration",
    category: "jwt",
    severity: "HIGH",
    owasp: "A07:2021 - Identification and Authentication Failures",
    cwe: "CWE-613",
    description: "Access tokens can remain valid indefinitely because expiration is missing or not verified.",
    confidenceScore: 0.87,
  },
  {
    id: "jwt.long-lived-access-token",
    title: "Long-lived access token",
    category: "jwt",
    severity: "MEDIUM",
    owasp: "A07:2021 - Identification and Authentication Failures",
    cwe: "CWE-613",
    description: "Access token lifetime is too long for a bearer token exposed to clients.",
    confidenceScore: 0.75,
  },
  {
    id: "jwt.weak-signing-secret",
    title: "Weak JWT signing secret",
    category: "jwt",
    severity: "HIGH",
    owasp: "A02:2021 - Cryptographic Failures",
    cwe: "CWE-326",
    description: "JWT signing relies on low-entropy or guessable secret material.",
    confidenceScore: 0.83,
  },
  {
    id: "jwt.token-in-local-storage",
    title: "JWT stored in localStorage",
    category: "jwt",
    severity: "MEDIUM",
    owasp: "A07:2021 - Identification and Authentication Failures",
    cwe: "CWE-922",
    description: "Bearer tokens stored in localStorage are exposed to script execution after XSS.",
    confidenceScore: 0.78,
  },
  {
    id: "jwt.missing-issuer-audience-validation",
    title: "JWT issuer or audience not validated",
    category: "jwt",
    severity: "MEDIUM",
    owasp: "A07:2021 - Identification and Authentication Failures",
    cwe: "CWE-347",
    description: "JWT verification does not validate issuer and audience claims.",
    confidenceScore: 0.8,
  },
  {
    id: "prisma.unscoped-user-query",
    title: "Prisma query missing owner scope",
    category: "prisma",
    severity: "HIGH",
    owasp: "A01:2021 - Broken Access Control",
    cwe: "CWE-639",
    description: "A Prisma query fetches tenant-owned data without owner or organization scoping.",
    confidenceScore: 0.83,
  },
  {
    id: "prisma.mass-assignment",
    title: "Mass assignment through Prisma data object",
    category: "prisma",
    severity: "MEDIUM",
    owasp: "A04:2021 - Insecure Design",
    cwe: "CWE-915",
    description: "Untrusted request data appears to be passed directly into Prisma create or update calls.",
    confidenceScore: 0.8,
  },
  {
    id: "prisma.missing-transaction-critical-write",
    title: "Critical write missing transaction",
    category: "prisma",
    severity: "MEDIUM",
    owasp: "A04:2021 - Insecure Design",
    cwe: "CWE-841",
    description: "A multi-step critical write can leave inconsistent state if one operation fails.",
    confidenceScore: 0.68,
  },
  {
    id: "sql.string-concatenated-query",
    title: "String-concatenated SQL query",
    category: "sql_injection",
    severity: "CRITICAL",
    owasp: "A03:2021 - Injection",
    cwe: "CWE-89",
    description: "SQL text is assembled with string concatenation or template interpolation.",
    confidenceScore: 0.9,
  },
  {
    id: "sql.unparameterized-where",
    title: "Unparameterized SQL WHERE clause",
    category: "sql_injection",
    severity: "HIGH",
    owasp: "A03:2021 - Injection",
    cwe: "CWE-89",
    description: "A WHERE clause appears to use untrusted values without parameter binding.",
    confidenceScore: 0.86,
  },
  {
    id: "xss.unsanitized-html",
    title: "Unsanitized HTML rendering",
    category: "xss",
    severity: "HIGH",
    owasp: "A03:2021 - Injection",
    cwe: "CWE-79",
    description: "HTML from untrusted or mixed-trust sources is rendered without sanitization.",
    confidenceScore: 0.88,
  },
  {
    id: "xss.unescaped-markdown",
    title: "Unsafe Markdown rendering",
    category: "xss",
    severity: "MEDIUM",
    owasp: "A03:2021 - Injection",
    cwe: "CWE-79",
    description: "Markdown rendering allows raw HTML or unsafe links without sanitization.",
    confidenceScore: 0.77,
  },
  {
    id: "xss.dom-injection",
    title: "DOM injection sink",
    category: "xss",
    severity: "HIGH",
    owasp: "A03:2021 - Injection",
    cwe: "CWE-79",
    description: "Untrusted data can reach a script-capable DOM sink.",
    confidenceScore: 0.86,
  },
  {
    id: "csrf.missing-csrf-protection",
    title: "Missing CSRF protection",
    category: "csrf",
    severity: "MEDIUM",
    owasp: "A01:2021 - Broken Access Control",
    cwe: "CWE-352",
    description: "Cookie-authenticated mutation routes do not require CSRF protection.",
    confidenceScore: 0.78,
  },
  {
    id: "csrf.state-changing-get",
    title: "State-changing GET request",
    category: "csrf",
    severity: "MEDIUM",
    owasp: "A01:2021 - Broken Access Control",
    cwe: "CWE-352",
    description: "A GET route appears to mutate state, making browser-triggered actions easier.",
    confidenceScore: 0.74,
  },
  {
    id: "csrf.cookie-samesite-none",
    title: "Cookie SameSite=None without strong controls",
    category: "csrf",
    severity: "MEDIUM",
    owasp: "A05:2021 - Security Misconfiguration",
    cwe: "CWE-352",
    description: "Cross-site cookies are enabled without compensating anti-CSRF controls.",
    confidenceScore: 0.76,
  },
  {
    id: "secrets.env-file-committed",
    title: "Environment file committed",
    category: "secrets",
    severity: "HIGH",
    owasp: "A02:2021 - Cryptographic Failures",
    cwe: "CWE-538",
    description: "A real environment file may expose production configuration or credentials.",
    confidenceScore: 0.86,
  },
  {
    id: "secrets.oauth-client-secret",
    title: "OAuth client secret exposed",
    category: "secrets",
    severity: "HIGH",
    owasp: "A02:2021 - Cryptographic Failures",
    cwe: "CWE-798",
    description: "OAuth client secret material appears in source or client-accessible code.",
    confidenceScore: 0.84,
  },
  {
    id: "rate-limit.missing-auth-rate-limit",
    title: "Authentication endpoint missing rate limit",
    category: "rate_limiting",
    severity: "HIGH",
    owasp: "A07:2021 - Identification and Authentication Failures",
    cwe: "CWE-307",
    description: "Login, registration, or token endpoints lack dedicated brute-force throttling.",
    confidenceScore: 0.84,
  },
  {
    id: "rate-limit.no-upload-rate-limit",
    title: "Upload endpoint missing rate limit",
    category: "rate_limiting",
    severity: "MEDIUM",
    owasp: "A04:2021 - Insecure Design",
    cwe: "CWE-770",
    description: "Repository upload or import endpoints can be abused to consume storage and compute.",
    confidenceScore: 0.8,
  },
  {
    id: "logging.sensitive-data-logged",
    title: "Sensitive data written to logs",
    category: "logging",
    severity: "MEDIUM",
    owasp: "A09:2021 - Security Logging and Monitoring Failures",
    cwe: "CWE-532",
    description: "Logs include secrets, passwords, tokens, or personally identifiable data.",
    confidenceScore: 0.82,
  },
  {
    id: "logging.missing-audit-log",
    title: "Missing audit logging for sensitive action",
    category: "logging",
    severity: "LOW",
    owasp: "A09:2021 - Security Logging and Monitoring Failures",
    cwe: "CWE-778",
    description: "Security-sensitive actions are not captured in audit logs.",
    confidenceScore: 0.65,
  },
  {
    id: "react.insecure-target-blank",
    title: "External link missing noopener",
    category: "react",
    severity: "LOW",
    owasp: "A05:2021 - Security Misconfiguration",
    cwe: "CWE-1022",
    description: "Links opened in a new tab can control the opener page without rel=noopener.",
    confidenceScore: 0.82,
  },
  {
    id: "react.untrusted-url-navigation",
    title: "Untrusted URL navigation",
    category: "react",
    severity: "MEDIUM",
    owasp: "A01:2021 - Broken Access Control",
    cwe: "CWE-601",
    description: "Client navigation trusts URLs that may be attacker-controlled.",
    confidenceScore: 0.76,
  },
  {
    id: "express.missing-json-limit",
    title: "Missing JSON body size limit",
    category: "express",
    severity: "MEDIUM",
    owasp: "A05:2021 - Security Misconfiguration",
    cwe: "CWE-770",
    description: "Express JSON parsing is configured without a bounded request body size.",
    confidenceScore: 0.78,
  },
  {
    id: "express.error-stack-leak",
    title: "Error stack exposed to clients",
    category: "express",
    severity: "MEDIUM",
    owasp: "A05:2021 - Security Misconfiguration",
    cwe: "CWE-209",
    description: "Production error responses may include stack traces or internal implementation details.",
    confidenceScore: 0.78,
  },
  {
    id: "helmet.csp-disabled",
    title: "Content Security Policy disabled",
    category: "helmet",
    severity: "MEDIUM",
    owasp: "A05:2021 - Security Misconfiguration",
    cwe: "CWE-1021",
    description: "Helmet is present but Content Security Policy is disabled or overly permissive.",
    confidenceScore: 0.74,
  },
  {
    id: "cors.credentials-wildcard",
    title: "Wildcard CORS with credentials",
    category: "cors",
    severity: "HIGH",
    owasp: "A05:2021 - Security Misconfiguration",
    cwe: "CWE-942",
    description: "Credentialed browser requests are allowed with an unsafe or reflected origin policy.",
    confidenceScore: 0.88,
  },
  {
    id: "validation.zod-passthrough",
    title: "Validation schema allows unknown fields",
    category: "validation",
    severity: "LOW",
    owasp: "A04:2021 - Insecure Design",
    cwe: "CWE-20",
    description: "Schema passthrough can allow unexpected properties into service or persistence layers.",
    confidenceScore: 0.68,
  },
  {
    id: "validation.unbounded-file-upload",
    title: "Unbounded file upload",
    category: "validation",
    severity: "HIGH",
    owasp: "A04:2021 - Insecure Design",
    cwe: "CWE-434",
    description: "File upload handling lacks clear size, type, extension, or archive limits.",
    confidenceScore: 0.84,
  },
  {
    id: "validation.missing-url-allowlist",
    title: "Missing URL allowlist validation",
    category: "validation",
    severity: "MEDIUM",
    owasp: "A10:2021 - Server-Side Request Forgery",
    cwe: "CWE-918",
    description: "Outbound URL or repository import logic does not clearly restrict allowed hosts.",
    confidenceScore: 0.78,
  },
  {
    id: "demo.hardcoded-secret",
    title: "Demo hardcoded secret finding",
    category: "secrets",
    severity: "HIGH",
    owasp: "A02:2021 - Cryptographic Failures",
    cwe: "CWE-798",
    description: "Demo-mode metadata for showing secret remediation workflows when live findings are unavailable.",
    confidenceScore: 0.6,
    tags: ["demo"],
  },
  {
    id: "demo.missing-input-validation",
    title: "Demo missing validation finding",
    category: "validation",
    severity: "MEDIUM",
    owasp: "A04:2021 - Insecure Design",
    cwe: "CWE-20",
    description: "Demo-mode metadata for showing input validation remediation workflows.",
    confidenceScore: 0.6,
    tags: ["demo"],
  },
  {
    id: "demo.unsafe-database-query",
    title: "Demo unsafe database query finding",
    category: "sql_injection",
    severity: "HIGH",
    owasp: "A03:2021 - Injection",
    cwe: "CWE-89",
    description: "Demo-mode metadata for showing SQL injection remediation workflows.",
    confidenceScore: 0.6,
    tags: ["demo"],
  },
  {
    id: "demo.weak-security-middleware",
    title: "Demo weak security middleware finding",
    category: "express",
    severity: "LOW",
    owasp: "A05:2021 - Security Misconfiguration",
    cwe: "CWE-693",
    description: "Demo-mode metadata for showing API hardening remediation workflows.",
    confidenceScore: 0.6,
    tags: ["demo"],
  },
];

export const securityKnowledgeBaseRules = RULE_SPECS.map(createKnowledgeBaseRule);

function createKnowledgeBaseRule(spec: RuleSpec): SecurityKnowledgeBaseRule {
  return {
    id: spec.id,
    title: spec.title,
    category: spec.category,
    severity: spec.severity,
    owasp: spec.owasp,
    cwe: spec.cwe,
    description: spec.description,
    businessImpact: spec.businessImpact ?? CATEGORY_BUSINESS_IMPACT[spec.category],
    technicalImpact: spec.technicalImpact ?? CATEGORY_TECHNICAL_IMPACT[spec.category],
    remediationSteps: spec.remediationSteps ?? DEFAULT_REMEDIATION_STEPS[spec.category],
    secureCodingRecommendations:
      spec.secureCodingRecommendations ?? DEFAULT_SECURE_CODING_RECOMMENDATIONS[spec.category],
    codeExample: spec.codeExample ?? DEFAULT_CODE_EXAMPLES[spec.category],
    externalReferences: spec.externalReferences ?? defaultReferences(spec),
    confidenceScore: clampConfidenceScore(spec.confidenceScore),
    tags: [...new Set([spec.category, ...inferTags(spec), ...(spec.tags ?? [])])].sort(),
  };
}

function defaultReferences(spec: RuleSpec): SecurityKnowledgeBaseReference[] {
  return spec.cwe ? [OWASP_TOP_10_REFERENCE, OWASP_CHEAT_SHEET_REFERENCE, CWE_REFERENCE] : [OWASP_TOP_10_REFERENCE];
}

function inferTags(spec: RuleSpec): string[] {
  return spec.id.split(/[.-]/).filter((part) => part.length > 2);
}

function clampConfidenceScore(value: number): number {
  return Math.max(0, Math.min(1, Number(value.toFixed(2))));
}
